README.md
enumeratum-core/src/main/scala/enumeratum/Enum.scala
enumeratum-core/src/test/scala/enumeratum/EnumSpec.scala
enumeratum-core/src/test/scala/enumeratum/Eval.scala
macros/src/main/scala/enumeratum/EnumMacros.scala
project/Build.scala

Looks like things *are* in order !

Try ordinals

---

enumeratum-core/src/main/scala/enumeratum/Enum.scala
enumeratum-core/src/test/scala/enumeratum/EnumSpec.scala

- Add test for -1 case when no such value exists

- Add valuesToIndex map for optimised index getting

---

enumeratum-core/src/main/scala/enumeratum/Enum.scala

Enum's mangled name used in previous version is not very useful, especially when used in conjunction with frameworks such as spray or akka-http where bubbled up exceptions are shown to end users as errors. Providing enum members seems as a better idea. Let me know what you think.

Improved exception messages

---

enumeratum-core/compat/src/main/scala-2.11/enumeratum/values/ValueEnum.scala

A bunch of stuff was copy pasted from EnumEntry and still referred to things like names

Fix ValueEnum names and Scaladocs

---

enumeratum-play-json/src/main/scala/enumeratum/EnumFormats.scala
enumeratum-play-json/src/test/scala/enumeratum/EnumFormatsSpec.scala

In Play JSON, a small number of constant strings are used for validation errors. These can then be [localized](https://github.com/playframework/playframework/blob/9a06b9a0a6ea7d1299e61ea3c1f37a08b714297e/framework/src/play/src/main/resources/messages.default). It also enables non-Play code to use this message, combined with the path specifying the bad field's location, to generate useful messages.
This change modifies the Play JSON `Reads` for enums to use strings already [in use](https://github.com/playframework/playframework/blob/bf29d718c426d1d30d10553ad2e6b609bc1091fe/framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala#L752) in Play. Although on their own they are less informative than what's there now, they fit in better with Play and when combined with paths can be …

Change error message for Play JSON to be like Play

---

README.md

Using `sealed abstract class State(override def entryName: String) extends EnumEntry`, as described in README.md, raises the following error : 
```
error: 'val' expected but 'def' found.
sealed abstract class State(override def entryName: String) extends EnumEntry
^
```
Using `sealed abstract class State(override val entryName: String) extends EnumEntry` instead compiles.

README.md : fix example with sealed abstract class

---

enumeratum-core/src/main/scala/enumeratum/EnumEntry.scala
enumeratum-core/src/test/scala/enumeratum/EnumSpec.scala

In my practice I experienced that it is a usual need to check whether an enum is contained by a list of enums. 
One way is Seq(E1,E2,..).contains(E) but i think the following syntax is more readable, intuitive and type-checked:
E.in(E1,E2,...).
Please consider if this approach is right. Thanks!

Type-safe and readable contains checking

---

enumeratum-circe/src/main/scala/enumeratum/Circe.scala
enumeratum-circe/src/test/scala/enumeratum/CirceSpec.scala
enumeratum-core/src/main/scala/enumeratum/Enum.scala
enumeratum-core/src/test/scala/enumeratum/EnumSpec.scala
enumeratum-play-json/src/main/scala/enumeratum/EnumFormats.scala
enumeratum-play-json/src/main/scala/enumeratum/PlayLowercaseJsonEnum.scala
enumeratum-play-json/src/main/scala/enumeratum/PlayUppercaseJsonEnum.scala
enumeratum-play-json/src/test/scala/enumeratum/EnumFormatsSpec.scala
enumeratum-play/src/main/scala/enumeratum/Forms.scala
enumeratum-play/src/main/scala/enumeratum/PlayLowercaseEnum.scala
enumeratum-play/src/main/scala/enumeratum/PlayLowercaseFormFieldEnum.scala
enumeratum-play/src/main/scala/enumeratum/PlayLowercasePathBindableEnum.scala
enumeratum-play/src/main/scala/enumeratum/PlayLowercaseQueryBindableEnum.scala
enumeratum-play/src/main/scala/enumeratum/PlayUppercaseEnum.scala
enumeratum-play/src/main/scala/enumeratum/PlayUppercaseFormFieldEnum.scala
enumeratum-play/src/main/scala/enumeratum/PlayUppercasePathBindableEnum.scala
enumeratum-play/src/main/scala/enumeratum/PlayUppercaseQueryBindableEnum.scala
enumeratum-play/src/main/scala/enumeratum/UrlBinders.scala
enumeratum-play/src/test/scala/enumeratum/FormSpec.scala
enumeratum-play/src/test/scala/enumeratum/UrlBindersSpec.scala
enumeratum-reactivemongo-bson/src/main/scala/enumeratum/EnumHandler.scala
enumeratum-reactivemongo-bson/src/test/scala/enumeratum/EnumBsonHandlerSpec.scala
enumeratum-upickle/src/main/scala/enumeratum/UPickler.scala
enumeratum-upickle/src/test/scala/enumeratum/UPickleSpec.scala

This pull request adds support for lower/upper case transformations. Unlike case sensitive, these transformations will **only** support lower or upper case. Futhermore, they also alter any decoders (or writers/unbind depending on the framework that is supporting them).
This was done because in my personal use case, this logic is defined all the time. As an example we have an ENUM that is represented in a database with uppercase enum values, however the REST interface (which is implemented in play) only has lowercase names (which means we have to handle bind and unbind  transforming the value, instead of just returning the original value). Same deal with Json formatters and such

Adds support for lower/uppercase transformations

---

README.md
enumeratum-play/src/main/scala/enumeratum/Forms.scala

This makes the various `format` methods non private. The reasoning is that, if you are unable to make your enums extend `PlayEnum` or its variants, the only way to create a mapping using an enum is to make a reference to it with the `enum` method, i.e.
```scala
val myEnumMapping = enumeratum.Forms.enum(MyEnum)
```
Unfortunately the only way you can use this mapping is by reference to a variable, not its type
```scala
Form(
mapping(
"field" -> myEnumMapping
)
)
```
This is because play doesn't have any way to bring an implicit `Mapping` into scope, only an implicit `Formatter`. Making the format non privates means that you can do this
```scala
object Formats {
implicit val myEnumFormat = enumeratum.Forms.format(MyEnum)
}
```
And then you can use plays `of` to summon an implicit `Format` …

Make format/s non private

---

enumeratum-core/src/main/scala/enumeratum/Enum.scala
enumeratum-core/src/test/scala/enumeratum/EnumSpec.scala
macros/src/main/scala/enumeratum/EnumMacros.scala

Added a macro to infer automatically the Enum object of an EnumEntry.
This can be used to simplify mappings, serialization, etc.. For example, we can now do:
* An automatic Play JSON Formats:
```
implicit def enumFormat[A <: EnumEntry : Enum]: Format[A] = EnumFormats.formats(implicitly[Enum[A]])
```
* An automatic Slick mapper:
```
implicit def enumMapper[A <: EnumEntry : Enum : ClassTag] = MappedColumnType.base[A, String](
sn => sn.entryName,
str => implicitly[Enum[A]].withName(str)
)
```
* An io.underscore Validator:
```
implicit def enumValidator2stringValidator[A <: EnumEntry : Enum](enumValidator: Validator[A]): Validator[String] =
Validator[String] { in => implicitly[Enum[A]].withNameOption(in) map enumValidator getOrElse fail("Value is required") }
```
Etc...

Infer Enum[A] from A <: EnumEntry

---

enumeratum-core/compat/src/main/scala-2.11/enumeratum/values/ValueEnum.scala
enumeratum-core/compat/src/test/scala-2.11/enumeratum/values/ValueEnumSpec.scala
enumeratum-core/src/main/scala/enumeratum/Enum.scala
enumeratum-core/src/test/scala/enumeratum/EnumSpec.scala
macros/compat/src/main/scala-2.10/enumeratum/ContextUtils.scala
macros/compat/src/main/scala-2.11/enumeratum/ContextUtils.scala
macros/src/main/scala/enumeratum/EnumMacros.scala

- Remove restraint on companion-materialising macro and move it macro project
- Add companion finding to ValueEnums as well
Note: It's hard to generalise this for use on ValueEnum[ValueType, EntryType] ... instead it's currently implemented for each type of value enum. C'est la vie? Or not enough macro 力?

Refactor companion object finding

---

macros/compat/src/main/scala-2.11/enumeratum/ValueEnumMacros.scala

Addresses #60
- Replace runtimeClass with runtimeClass.getSimpleName
- Add a note for nested ValueEnums

Add a better error message for ValueEnum macro

---

README.md
benchmarking/src/main/scala/enumeratum/StdLibEnumBenchmarks.scala
benchmarking/src/main/scala/enumeratum/Weekday.scala
benchmarking/src/main/scala/enumeratum/Workday.scala

Turns out Enumeratum is around 4x faster than the standard library's `Enumeration`.

Add benchmarks against standard library

---

README.md
enumeratum-core/compat/src/test/scala-2.11/enumeratum/values/Animal.scala
enumeratum-core/compat/src/test/scala-2.11/enumeratum/values/ValueEnumHelpers.scala
enumeratum-core/compat/src/test/scala-2.11/enumeratum/values/ValueEnumSpec.scala
macros/compat/src/main/scala-2.11/enumeratum/ValueEnumMacros.scala

By resolving the constructor of `ValueEntryType`'s parameters lists using its `WeakTypeTag`,
we no longer care if the constructor method call's `.tpe` returns null when the enum members are instantiated.
Subsequently, `ValueEnum`s now work in the REPL.
This opens the door to porting `ValueEnum`s to 2.10.x, but there are still a few API differences that need to be bridged, such as `isConstructor`, `paramsList`, and `TermName` extractor.
Closes #60

Closes #60 Add support for nested ValueEnums

---

enumeratum-core/compat/src/test/scala-2.11/enumeratum/values/CustomEnumPrivateConstructor.scala
enumeratum-core/compat/src/test/scala-2.11/enumeratum/values/ValueEnumSpec.scala
macros/compat/src/main/scala-2.11/enumeratum/ValueEnumMacros.scala

In 1.4.11, the macro started only looking for public constructor methods. There was no reason
for this change at all, so it has been reverted.
A test case has been added to prevent regressions.

Closes #66 Fix ValueEnums not working with private constructors

---

README.md
enumeratum-core/src/main/scala/enumeratum/values/ValueEnum.scala
enumeratum-core/src/main/scala/enumeratum/values/ValueEnumEntry.scala
macros/src/main/scala/enumeratum/EnumMacros.scala

This PR
- Extends ValueEnumOps to value class.
- Remove unnecessary filter in enclosedSubClassTrees method (`isModule` filter had already been applied on `enclosingBodySubClassTrees` in preceding `enclosingModule.impl.body.filter`)
- Fix some trivial typos.

Remove unnecessary filter in enclosedSubClassTrees etc

---

README.md

Solves #84 by making it more explicit the existence of a safe method to get an instance of Enum by its name

Add Enum.withNameOption example usage to README

---

README.md
enumeratum-core/src/main/scala/enumeratum/EnumEntry.scala
enumeratum-core/src/test/scala/enumeratum/EnumSpec.scala
enumeratum-core/src/test/scala/enumeratum/Models.scala

Previously, I was defining enum types as sealed case objects and overriding `toString` to get the correct formatting when required. For example, instead of the string `"CarModel"`, I wanted `toString` to give `"Car Model"`. `Enumeratum` has limited ability to override the name behaviour, unfortunately, splitting PascalCase to words is not provided.
In this pull request, the stackable traits `UpperSnakecase`, `CapitalSnakecase`, `Hyphencase`, `UpperHyphencase`, `CapitalHyphencase`, `Dotcase`, `UpperDotcase`, `CapitalDotcase`, `Words`, `UpperWords` and `CapitalWords` are provided. This greatly expands `Enumeratum`'s capacity to override name behaviour.

Additional stackable traits added to EnumEntry

---

README.md

Added examples of usage for the following methods: `withNameInsensitive`, `withNameInsensitiveOption`, `withNameUppercaseOnly`, `withNameUppercaseOnlyOption`, `withNameLowercaseOnly` and `withNameLowercaseOnlyOption`.

Added examples to Usage section of README

---

enumeratum-core/src/main/scala/enumeratum/EnumEntry.scala

Instead of using abstract override, just override and refer to a stable
private lazy val that refers to super.entryName. Lazy is used because
we don't want to create and store the String if users don't need to
serialise their enums.
Performance comparison (spoiler, in stacked case ~500x faster)
```
Before:
[info] Benchmark                         Mode  Cnt     Score    Error  Units
[info] EnumBenchmarks.entryNameStacked   avgt   30  1499.862 ± 34.588  ns/op
[info] EnumBenchmarks.entryNameStandard  avgt   30     4.461 ±  0.087  ns/op
After:
[info] Benchmark                         Mode  Cnt  Score   Error  Units
[info] EnumBenchmarks.entryNameStacked   avgt   30  3.180 ± 0.040  ns/op
[info] EnumBenchmarks.entryNameStandard  avgt   30  3.185 ± 0.075  ns/op
```

Closes #105: Optimise entryName in stackable traits

---

enumeratum-core/src/test/scala/enumeratum/EnumSpec.scala
macros/src/main/scala/enumeratum/EnumMacros.scala

Instead of letting the compiler fail with a NoSymbol error, try to catch
it during compilation and offer up a more informative error message.

Improve the error message thrown when a companion object cannot be found

---

build.sbt
project/Versions.scala

Core and libs will be bumped to use the newer version when there is something more significant (fix or feature).
This mostly just improves an error message.

Release/macros 1.5.7

---

benchmarking/src/main/java/testing/JAgeGroup.java
benchmarking/src/main/scala/enumeratum/MapComparisons.scala
benchmarking/src/main/scala/enumeratum/SetComparisons.scala

- Add comparisons for Java EnumSet and Scala Set
- Add Map comparisons
Results
-------
```
[info] Benchmark                                  Mode  Cnt   Score   Error  Units
[info] MapComparisons.enumeratumScalaMapGet       avgt   30   9.830 ± 0.207  ns/op
[info] MapComparisons.jEnumEnumMapGet             avgt   30   4.745 ± 0.685  ns/op
[info] MapComparisons.jEnumScalaMapGet            avgt   30  12.204 ± 0.186  ns/op
[info] SetComparisons.enumeratumScalaSetContains  avgt   30   7.670 ± 1.333  ns/op
[info] SetComparisons.jEnumEnumSetContains        avgt   30   4.391 ± 0.077  ns/op
[info] SetComparisons.jEnumScalaSetContains       avgt   30   8.906 ± 0.235  ns/op
```
Discussion
----------
There is no denying that Java  EnumMap and EnumSet are fast. Given that JMH supposedly has
an over …

Enum Set and Map comparisons

---

benchmarking/src/main/scala/enumeratum/SetComparisons.scala

Results
-------
```
[info] Benchmark                                         Mode  Cnt   Score   Error  Units
[info] SetComparisons.enumeratumScalaSetSubsetOfSmall   avgt   30   9.248 ± 0.109  ns/op
[info] SetComparisons.enumeratumScalaSetSubsetOfMedium  avgt   30  29.358 ± 0.287  ns/op
[info] SetComparisons.enumeratumScalaSetSubsetOfAll     avgt   30   2.469 ± 0.012  ns/op
[info] SetComparisons.jEnumEnumSetContainsAllSmall      avgt   30   3.888 ± 0.953  ns/op
[info] SetComparisons.jEnumEnumSetContainsAllMedium     avgt   30   3.457 ± 0.127  ns/op
[info] SetComparisons.jEnumEnumSetContainsAllAll        avgt   30   3.321 ± 0.827  ns/op
```
Discussion
----------
As expected, we have O(m) for subset checking on a Set of m elements against one of n elements.
Looking at the source code …

Add containsAll/subSetOf comparisons

---

benchmarking/src/main/scala/enumeratum/SetComparisons.scala
enumeratum-core/src/main/scala/enumeratum/EnumEntry.scala

For a more detailed look at the why it is currently an abstract class,
take a look at the issue on Github
Performance-wise, there is a consistent, statistically significant
sub-nanosecond difference, but it's not very big.
```
Abstract class
----------------
1st
[info] Benchmark                         Mode  Cnt  Score   Error  Units
[info] EnumBenchmarks.entryNameStacked   avgt   30  3.150 ± 0.023  ns/op
[info] EnumBenchmarks.entryNameStandard  avgt   30  3.121 ± 0.029  ns/op
2nd
[info] Benchmark                         Mode  Cnt  Score   Error  Units
[info] EnumBenchmarks.entryNameStacked   avgt   30  3.173 ± 0.037  ns/op
[info] EnumBenchmarks.entryNameStandard  avgt   30  3.123 ± 0.024  ns/op
3rd
[info] Benchmark                         Mode  Cnt  Score   Error  Units
[info] …
```

Referencing #116 Try making EnumEntry a Trait

---

enumeratum-json4s/src/main/scala/enumeratum/Json4s.scala
enumeratum-json4s/src/test/scala/enumeratum/Json4sSpec.scala

I ran into an issue where an enum was not deserializing in the expected manner using Json4s. After a bit of debugging, it turns out Json4s uses a separate serializer to convert keys.
The `CustomKeySerializer` class is nearly identical to the `CustomSerializer` class, so it creating a new helper was fairly straightforward, once it's need became apparent.

Implement Json4s CustomKeySerializer

---

README.md

fix typo in the slick documentation

---

.travis.yml
build.sbt
enumeratum-play/src/test/scala/enumeratum/PlayEnumSpec.scala
enumeratum-play/src/test/scala/enumeratum/values/PlayValueEnumHelpers.scala
macros/src/test/scala/enumeratum/CompilationSpec.scala
scala_2_12/note

[WIP] Upgrade/play 2.6.0 m

---

build.sbt

I messed up and forgot to explicitly set the `name` property.
This PR fixes that. The way I tested it was:
* run `sbt "scalacheck-aggregate/publishLocal"`
* make sure that `.ivy2/local/com.beachape/enumeratum-scalacheck_2.12/` and `.ivy2/local/com.beachape/enumeratum-scalacheck_sjs0.6_2.12/` got created.
Hopefully I didn't miss anything else...

Fix enumeratum-scalacheck artifact names

---

README.md
build.sbt
enumeratum-quill/src/main/scala/enumeratum/Quill.scala
enumeratum-quill/src/main/scala/enumeratum/QuillEnum.scala
enumeratum-quill/src/main/scala/enumeratum/values/Quill.scala
enumeratum-quill/src/main/scala/enumeratum/values/QuillValueEnum.scala
enumeratum-quill/src/test/scala/enumeratum/QuillEnumSpec.scala
enumeratum-quill/src/test/scala/enumeratum/values/QuillValueEnumSpec.scala
publish-integration-libs

As mentioned in #163.
Adds `QuillEnum` trait to automatically convert `EnumEntry`s to/from their `entryName`.
Adds `QuillValueEnum` trait to automatically convert `ValueEnumEntry`s to/from their `value`s.
I wasn't sure what to put for the `version`, so I left it as `0.1.0-SNAPSHOT`.

Add enumeratum-quill

---

README.md

Should be a [Type Ascription](https://docs.scala-lang.org/style/types.html#ascription) instead of an explicit cast or Type Annotation.

Update Quill Integration notes in README

---

build.sbt
enumeratum-core/src/main/scala/enumeratum/Enum.scala
enumeratum-core/src/main/scala/enumeratum/EnumEntry.scala
enumeratum-core/src/test/scala/enumeratum/EnumSpec.scala
enumeratum-core/src/test/scala/enumeratum/Models.scala

Adds support for `MultiEnum`, which maps multiple entries to a single enum. Also uses `breakOut` for some minor memory optimization.

Many to one

---

enumeratum-circe/src/main/scala/enumeratum/values/Circe.scala
enumeratum-circe/src/main/scala/enumeratum/values/CirceValueEnum.scala
enumeratum-circe/src/test/scala/enumeratum/values/CirceValueEnumSpec.scala
project/build.properties
project/plugins.sbt

Thought that it was a nice addition to the `CirceStringEnum` to be able to be used as a key in `Map`s (i.e.: `Map[MyEnum, Int]`).
For that, Circe requires a `KeyEncoder` and a `KeyDecoder` to be present in the implicit scope. With current enumeratum's API, implementing those is trivial for enums that are based on strings, so it could be cool to provide it out of the box.

Circe KeyEncoder/KeyDecoder for String Enum

---

README.md
build.sbt
enumeratum-cats/src/main/scala/enumeratum/Cats.scala
enumeratum-cats/src/main/scala/enumeratum/CatsEnum.scala
enumeratum-cats/src/main/scala/enumeratum/values/Cats.scala
enumeratum-cats/src/main/scala/enumeratum/values/CatsValueEnum.scala
enumeratum-cats/src/test/scala/enumeratum/CatsEnumSpec.scala
enumeratum-cats/src/test/scala/enumeratum/values/CatsOrderValueEnumSpec.scala
enumeratum-cats/src/test/scala/enumeratum/values/CatsValueEnumSpec.scala

This PR adds support for some basic type classes from `cats-core`:
- `Eq` for typesafe comparison
- `Show` for pretty printing
- `Hash` for abstracting of hashing of values
Corresponding enumeratum-style mixins are provided for these, supporting both `Enum` and `ValueEnum`. The second also comes in an extended version which provides an instance of `Order`.
Major use cases are generic derivation and operations on collections of (nested) enum values, for example sorting a list of errors by their (enum) priority. See `Readme.md` for small examples.

Add cats module

---

build.sbt

Circe had a minor release bump to `0.11.0` on 2018/12/18. Want to ensure enumeratum maintains functional parity with this new release.

Bump Circe version to 0.11.0

---

build.sbt
enumeratum-core-jvm-tests/src/test/scala/enumeratum/Eval.scala
project/plugins.sbt

Closes #211 
Resolve the PR snapshot versions to just major minor in terms of target directory.
Tested locally using instructions in #211:
```
sbt:enumeratum-root> ++2.12.9-bin-f96c8d2-SNAPSHOT!
[info] Forcing Scala version to 2.12.9-bin-f96c8d2-SNAPSHOT on all projects.
[info] Reapplying settings...
[info] Set current project to enumeratum-root (in build file:/Users/lloyd/Documents/skala/enumeratum/)
sbt:enumeratum-root> coreJVMTests/test
[info] EnumJVMSpec:
[info] findValues Vector
[info] - should be in the same order that the objects were declared in
[info] ValueEnumJVMSpec:
[info] IntEnum withValue
[info] - should return proper members for valid values but throw otherwise
[info] LongEnum withValue
[info] - should return proper members for valid values but throw otherwise
[info] …
```

Fix Eval so that it finds the classes directory for PR Snapshots

---

enumeratum-circe/src/main/scala/enumeratum/Circe.scala
enumeratum-circe/src/main/scala/enumeratum/CirceKeyEnum.scala
enumeratum-circe/src/test/scala/enumeratum/CirceKeySpec.scala
enumeratum-circe/src/test/scala/enumeratum/ShirtSize.scala

It will be nice to have key encoder/decoder for non-value based enums, since there is one for string enum.

Circe KeyEncoder/KeyDecoder for Enum

---

build.sbt
enumeratum-doobie/src/main/scala/enumeratum/Doobie.scala
enumeratum-doobie/src/main/scala/enumeratum/DoobieEnum.scala
enumeratum-doobie/src/main/scala/enumeratum/values/Doobie.scala
enumeratum-doobie/src/main/scala/enumeratum/values/DoobieValueEnum.scala
enumeratum-doobie/src/test/scala/enumeratum/DoobieEnumSpec.scala
enumeratum-doobie/src/test/scala/enumeratum/values/DoobieValueEnumSpec.scala

closes https://github.com/lloydmeta/enumeratum/issues/186
The tests that I added only check whether there is a Read and Write for the enum types. They do not check however that the resulting values look good. The reason is to avoid adding extra dependencies like cats-effect and using an actual database like h2 or PostgreSQL. I could add them if necessary.
Also, for the version of the enumeratum-doobie module, I am not too sure where should it start.

Adds support for doobie

---

.travis.yml
build.sbt
enumeratum-core/src/main/scala/enumeratum/values/ValueEnum.scala
enumeratum-play-json/src/main/scala/enumeratum/values/EnumFormats.scala
enumeratum-play/compat/src/test/scala-2.10/enumeratum/helpers/ActionHelper.scala
enumeratum-play/compat/src/test/scala-2.11/enumeratum/helpers/ActionHelper.scala
enumeratum-play/compat/src/test/scala-2.13/enumeratum/helpers/ActionHelper.scala
enumeratum-play/src/main/scala/enumeratum/UrlBinders.scala
enumeratum-play/src/main/scala/enumeratum/values/UrlBinders.scala
enumeratum-play/src/test/scala/enumeratum/PlayEnumSpec.scala
enumeratum-play/src/test/scala/enumeratum/values/PlayValueEnumHelpers.scala
macros/src/main/scala/enumeratum/EnumMacros.scala
macros/src/main/scala/enumeratum/ValueEnumMacros.scala
project/plugins.sbt

Changes:
- ~Drops Play support for 2.10.x~
- Removes WartRemover (for now? might change if [this](https://stackoverflow.com/questions/56411871/choosing-sbt-plugin-version-based-on-cross-scala-version-for-sbt-1-x) gets answered)
Weirdness:
- ~For some reason, the 2.10.x travis build required me to publish a snapshot artefact...for 2.12...~

2.13 RC branch merge

---

build.sbt

Hi, I noticed that enumeratum_circe has not published on 2.13 yet. Circe is available for 2.13 via `0.12.0-M4`. Tests pass on this version without modification.

Update circe version for publishing enumeratum-circe on 2.13 (jvm+js)

---

build.sbt

This is not needed as of circe 0.12.0
Confirmed in release notes: https://github.com/circe/circe/releases/tag/v0.12.0
circe/circe#1245 has discussion on it not being needed and resolution.

Remove dependency on circe not-java-time in JS enumeratum-circe

---

README.md

A NoSuchElementException is thrown if no match is found.

Correct exception type in Readme

---

README.md

At the moment, `Enumeratum`'s `README` file lacks usage instructions for `enumeratum-doobie`.
The aim of this PR is to include them.
This reuses the same "pattern" and examples used for `enumeratm-quill` usage instructions, of course adapted for `doobie`.

Updated README to include enumeratum-doobie usage instructions

---

README.md
build.sbt
enumeratum-core/src/test/scala/enumeratum/values/ValueEnumSpec.scala
macros/src/main/scala/enumeratum/ValueEnumMacros.scala
macros/src/main/scala/enumeratum/values/AllowAlias.scala

Hello! 👋
I'd like to use enumeratum to model [protobuf enumerations](https://developers.google.com/protocol-buffers/docs/proto3#enum). Protobuf allows you to define aliases in your enums, so I've added a marker trait to allow me to disable the unique-values check in the macro.
WDYT?

Allow aliases in value enums

---

README.md
build.sbt
enumeratum-reactivemongo-bson/src/main/scala/enumeratum/EnumHandler.scala
enumeratum-reactivemongo-bson/src/main/scala/enumeratum/ReactiveMongoBsonEnum.scala
enumeratum-reactivemongo-bson/src/main/scala/enumeratum/values/BSONValueHandlers.scala
enumeratum-reactivemongo-bson/src/main/scala/enumeratum/values/EnumHandler.scala
enumeratum-reactivemongo-bson/src/main/scala/enumeratum/values/ReactiveMongoBsonValueEnum.scala
enumeratum-reactivemongo-bson/src/test/scala/enumeratum/EnumBsonHandlerSpec.scala
enumeratum-reactivemongo-bson/src/test/scala/enumeratum/ReactiveMongoBsonEnumSpec.scala
enumeratum-reactivemongo-bson/src/test/scala/enumeratum/values/EnumBsonHandlerHelpers.scala
enumeratum-reactivemongo-bson/src/test/scala/enumeratum/values/EnumBsonHandlerSpec.scala

reactive-mongo 0.19.x introduced a huge refactoring which is aimed to stabilize an API for version 1.0. The new API is not backward compatible and requires a rework of the previous enumeratum handlers.
This refactoring also removed support for Scala 2.10 for the new API libraries which is my 2.10 is also removed for this enumeratum module.

Adapting Enum Handlers to new reactive-mongo API

---

.travis-jvmopts
.travis.yml
README.md
build.sbt
enumeratum-play-json/src/main/scala/enumeratum/PlayJsonEnum.scala
publish-integration-libs

In play-json `2.8.x`, the writes trait was [changed](https://github.com/playframework/play-json/pull/216) from `Writes[-T]` (contravariant) to `Writes[T]` (invariant) which breaks enumeratum's `PlayJsonEnum` trait. This PR does the following:
- Adds an implicit helper to contraMap the `Writes` provided by the existing trait. This seems to be sufficient enough to support play-json `2.8.x` without any more complicated code changes.
- Drops Scala 2.10 support. While working on this PR there were a few sporadic dependency resolution issues with resolving 2.10 based dependencies, but now I'm unable to resolve any of the 2.10 dependencies when building the project, so I've elected to drop 2.10 support with this PR.
- Cleans up `build.sbt` now that it seems like Scala 2.13 is supported on all …

Adds Play 2.8.x support, drops Scala 2.10 support

---

build.sbt

There is no need to pull in reactivemongo, the driver, since all we are
concerned with is the BSON API.
Also, starting with version 0.19.6, there are now two variants, a noshaded
version and a version which has Netty integrated into it for projects using
Netty themselves avoiding incompatibilities.
Since we do not know in advance which library is choosen in a project, make the
dependency a "provided" one.

reactivemongo: Only depend on the bson-api, noshaded variant

---

enumeratum-core/src/main/scala/enumeratum/EnumEntry.scala
enumeratum-core/src/test/scala/enumeratum/EnumSpec.scala
enumeratum-core/src/test/scala/enumeratum/Models.scala

Hi, I've found a bug where `CamelCase` like enumeration is recognized as `Camelcase` instead of `CamelCase`
This should hopefully fixes that problem.
I have added some test along with this

CamelCase enum should be recognized

---

README.md

Due to misunderstanding that can appear [like here](https://github.com/lloydmeta/enumeratum/issues/277) I think it would be better to add schema db description. It will help to get entire picture of example

Extended doobie example description

---

README.md
build.sbt
enumeratum-core/src/test/scala/enumeratum/EnumSpec.scala
enumeratum-core/src/test/scala/enumeratum/Models.scala
macros/src/main/scala/enumeratum/EnumMacros.scala

This updates the `findValues` macro to recursively search the bodies of objects defined within the companion object, e.g.
```scala
sealed trait Thing extends EnumEntry
object Thing extends Enum[Thing] {
object nested {
// this object is found now
case object Foo extends Thing
object nested2 {
// this is found too
case object Bar extends Thing {
// even this one is found
case object Baz extends Thing
}
}
}
}
```
Note: I expect CI will fail since [build.sbt references the stable version of enumeratum-macros](https://github.com/lloydmeta/enumeratum/blob/master/build.sbt#L186) which doesn't contain these changes. I tested locally by uncommenting the `dependsOn(macros)` line, but figured I shouldn't commit that. Let me know what the right workflow is for getting everything up to date.

Find members in nested objects

---

build.sbt
project/Versions.scala

Releases 1.6.1 for the following ScalaJS 1.0 modules
- Macros
- Core
- Circe
- Cats
- Scalacheck

[Release] 1.6.1 release for all ScalaJS 1.0 compat projects

---

README.md
build.sbt
enumeratum-play-json/src/main/scala/enumeratum/PlayInsensitiveJsonEnum.scala
enumeratum-play-json/src/main/scala/enumeratum/PlayLowercaseJsonEnum.scala
enumeratum-play-json/src/main/scala/enumeratum/PlayUppercaseJsonEnum.scala
enumeratum-play-json/src/test/scala/enumeratum/Dummy.scala
enumeratum-play-json/src/test/scala/enumeratum/EnumFormatsSpec.scala
enumeratum-play-json/src/test/scala/enumeratum/PlayJsonEnumSpec.scala
enumeratum-play-json/src/test/scala/enumeratum/values/EnumFormatsSpec.scala
enumeratum-play-json/src/test/scala/enumeratum/values/EnumJsonFormatHelpers.scala

+ Reinstates play-json js project
- scala `2.12.x` and `2.13.x` => `2.9.0`
- scala `2.11.x` => js still not supported (and unlikely in the future)
+ Reinstates argonaut js project
- scala `2.12.x` and `2.13.x` => `6.3.0`
- scala `2.11.x` => `6.2.5`
+ Fixes regression (#279) introduced in (#269)
- Test cases added in play-json module that would have caught the regression
+ Bumps play to `2.8.0` for scala `2.12.x` and `2.13.x`

Play json & Argonaut sjs 1.x support

---

README.md

Basically replaces `com.beachape/enumeratum_(?)2.11` -> `com.beachape/enumeratum_($1)2.12`
Cause it leads to 2.11 latest links like https://search.maven.org/artifact/com.beachape/enumeratum_2.11/1.6.1/jar

Update badges to 2.12

---

enumeratum-play-json/src/main/scala/enumeratum/EnumFormats.scala
enumeratum-play-json/src/main/scala/enumeratum/PlayInsensitiveJsonEnum.scala
enumeratum-play-json/src/main/scala/enumeratum/PlayJsonEnum.scala
enumeratum-play-json/src/main/scala/enumeratum/PlayLowercaseJsonEnum.scala
enumeratum-play-json/src/main/scala/enumeratum/PlayUppercaseJsonEnum.scala
enumeratum-play-json/src/test/scala/enumeratum/EnumFormatsSpec.scala
enumeratum-play-json/src/test/scala/enumeratum/PlayJsonEnumSpec.scala

Required to use enum in `Map` with Play-JSON

Play-JSON KeyReads & KeyWrites

---

build.sbt

Without this, it dies trying to download QuillJS deps which don't exist

Allows IntelliJ to import properly.

---

.gitignore
build.sbt

This is just what the title says.
Doobie 1.0.0-RC1 is compatible with 0.13.4, but sbt complains when doobie 1.0.0-RC2 and enumeratum-doobie are used together.
In our project, setting an exclusion rule works, but it would be nice to have an out of the box working version.
I don't know what you policy about release candidates is, but I also believe that many users are on the RC.
Many thanks!

bump doobie

---

enumeratum-core/src/main/scala/enumeratum/EnumEntry.scala

Make `enumEntry: A` private to improve ergonomics, because you cannot call `RandomEnumEntry.enumEntry.enumEntry.enumEntry` and so on. Also it's a good practice to make them private.

make wrapped value private in EnumEntryOps

---

build.sbt
project/plugins.sbt

Add Scala Native cross-builds

---

build.sbt
enumeratum-slick/src/test/scala/enumeratum/SlickEnumSupportSpec.scala

Update slick 3.4.1
I would like to use this library with play + slick. [The latest play-slick](https://mvnrepository.com/artifact/com.typesafe.play/play-slick_2.13/5.1.0) conforms to slick 3.4.1 and conflicts with the version of slick that enumeratum-slick depends on.

Update slick (3.4.1)

---

build.sbt

Wondering if we could cut a release to get the dependencies up?
```
[error]         * com.typesafe.slick:slick_2.13:3.5.1 (pvp) is selected over {3.5.0, 3.4.1}
[error]             +- com.byteslounge:slick-repo_2.13:1.8.1              (depends on 3.5.1)
[error]             +- com.typesafe.slick:slick-hikaricp_2.13:3.5.1       (depends on 3.5.1)
[error]             +- com.beachape:enumeratum-slick_2.13:1.7.5           (depends on 3.5.0)
```

Update to the latest slick version

---

enumeratum-core/src/test/scala/enumeratum/values/ValueEnumSpec.scala
macros/src/main/scala-3/enumeratum/ValueEnumMacros.scala
macros/src/test/scala/enumeratum/CompilationSpec.scala

simplify and correct finding the constructor param index for the value param.
As a follow-up, I want to double-check whether we need to require -Yretain-trees.
Some of the boyscouting here is a matter of taste, if it's not to yours, I'm happy to revert.

allow value constructor param to be any constructor parameter, rather than only the first

---

enumeratum-core/src/main/scala/enumeratum/EnumEntry.scala

https://github.com/lloydmeta/enumeratum/issues/415

415 EnumEntry.uncapitalize is no longer safe to use .tail on empty String since Scala 2.13.16
