- enumeratum-core/src/main/scala/enumeratum/Enum.scala
- enumeratum-core/src/test/scala/enumeratum/EnumSpec.scala
I would like to add withNameInsensitive, like withName but case insensitive. Tests added, matching withNameInsensitiveOption, and passed
> Added withNameInsensitive and tests

- README.md
- enumeratum-core/src/main/scala/enumeratum/Enum.scala
- project/plugins.sbt
Also:
- DRY up not found message
- Update readme
> Bump Coveralls plugin version from BETA to 1.0.0 release

- README.md
- Fix link to advanced SBT, styling
- Move play SBT support section closer to the top
- Add macro ala cart
> - Be a bit bolder, restructure installation instructions

- README.md
- enumeratum-core/src/main/scala/enumeratum/Enum.scala
- enumeratum-core/src/main/scala/enumeratum/EnumEntry.scala
- enumeratum-play/src/main/scala/enumeratum/PlayFormFieldEnum.scala
- enumeratum-play/src/main/scala/enumeratum/PlayPathBindableEnum.scala
- enumeratum-play/src/main/scala/enumeratum/PlayQueryBindableEnum.scala
- enumeratum-play/src/test/scala/enumeratum/PlayEnumSpec.scala
- Add SIRD router extractor support
- Improve performance of error messages when enum binding fails by caching the string lazily
- Improve Snakify function by using precompiled regex
> Play SIRD router support, performance improvements

- enumeratum-reactivemongo-bson/compat/src/main/scala-2.11/enumeratum/values/BSONValueHandlers.scala
- enumeratum-reactivemongo-bson/compat/src/main/scala-2.11/enumeratum/values/EnumHandler.scala
- enumeratum-reactivemongo-bson/compat/src/main/scala-2.11/enumeratum/values/ReactiveMongoBsonValueEnum.scala
- enumeratum-reactivemongo-bson/compat/src/test/scala-2.11/enumeratum/values/EnumBsonHandlerSpec.scala
- enumeratum-reactivemongo-bson/src/main/scala/enumeratum/EnumHandler.scala
- Optimise Reading BSON values
- Rename handler to bsonHandler for consistency
- Add check for convertable to Short
> Refactor ReactiveMongo code

- README.md
This information is missing from the readme, I had to look into the source code.
> add PlayFormFieldEnum documentation

- enumeratum-core/compat/src/main/scala-2.11/enumeratum/values/ValueEnumEntry.scala
- enumeratum-core/compat/src/test/scala-2.11/enumeratum/values/ValueEnumHelpers.scala
- enumeratum-core/src/main/scala/enumeratum/EnumEntry.scala
- Minor refactoring of code
- Add a in(Seq[A]) method out of kindness
- Add .in support to ValueEnums and add tests as well
> Add .in support to ValueEnums as well

- .travis.yml
- project/plugins.sbt
See [this blog post](http://www.warski.org/blog/2016/02/add-a-dependencies-badge-tree-to-your-project-using-updateimpact/)
> Add SBT plugin for sending dependency impact to update impact

- README.md
Add an example to the documentation.
> Documentation on how to use slick interpolated queries.

- README.md
- build.sbt
- enumeratum-argonaut/src/main/scala/enumeratum/ArgonautEnum.scala
- enumeratum-argonaut/src/main/scala/enumeratum/Argonauter.scala
- enumeratum-argonaut/src/main/scala/enumeratum/values/ArgonautValueEnum.scala
- enumeratum-argonaut/src/main/scala/enumeratum/values/Argonauter.scala
- enumeratum-argonaut/src/main/scala/enumeratum/values/package.scala
- enumeratum-argonaut/src/test/scala/enumeratum/ArgonautSpec.scala
- enumeratum-argonaut/src/test/scala/enumeratum/TrafficLight.scala
- enumeratum-argonaut/src/test/scala/enumeratum/values/ArgonautValueEnumSpec.scala
Support for encoding and decoding values using Argonaut.
> Add support for Argonaut

- .travis.yml
- build.sbt
- enumeratum-core/src/main/scala/enumeratum/Enum.scala
- enumeratum-core/src/main/scala/enumeratum/values/ValueEnum.scala
- macros/compat/src/main/scala-2.10/enumeratum/ContextUtils.scala
- macros/src/main/scala/enumeratum/EnumMacros.scala
- macros/src/main/scala/enumeratum/ValueEnumMacros.scala
> Make all enumeratum collections explicitly immutable

- build.sbt
> Add ReactiveMongo to 2.12 project

- README.md
- build.sbt
- cross-task
- enumeratum-test/src/main/scala/enumeratum/Models.scala
- enumeratum-test/src/main/scala/enumeratum/values/Alphabet.scala
- enumeratum-test/src/main/scala/enumeratum/values/Animal.scala
- enumeratum-test/src/main/scala/enumeratum/values/Bites.scala
- enumeratum-test/src/main/scala/enumeratum/values/ContentType.scala
- enumeratum-test/src/main/scala/enumeratum/values/Drinks.scala
- enumeratum-test/src/main/scala/enumeratum/values/LibraryItem.scala
- enumeratum-test/src/main/scala/enumeratum/values/MovieGenre.scala
- enumeratum-test/src/main/scala/enumeratum/values/OperatingSystem.scala
- project/Versions.scala
- project/plugins.sbt
- publish-signed
Relates to #92 
- Make it easy to run all tests for all projects at once (keep root? but disable publishing from it)
- Cross publish against all Scala/JS versions for each individual project. Sbt seems annoying to deal with, so maybe a nice bash script?
> Per-project versioning

- benchmarking/src/main/scala/enumeratum/EnumBenchmarks.scala
- benchmarking/src/main/scala/enumeratum/StackedEnum.scala
- project/plugins.sbt
- Add benchmarks for entryName
- Bump sbt-jmh version
> Add benchmarks for entryName

- README.md
- build.sbt
- enumeratum-json4s/src/main/scala/enumeratum/Json4s.scala
- enumeratum-json4s/src/main/scala/enumeratum/values/Json4s.scala
- enumeratum-json4s/src/test/scala/enumeratum/Json4sSpec.scala
- enumeratum-json4s/src/test/scala/enumeratum/TrafficLight.scala
- enumeratum-json4s/src/test/scala/enumeratum/values/Json4sValueEnumSpec.scala
- publish-integration-libs
> Json4s integration, fixes #121

- README.md
- enumeratum-core/src/main/scala/enumeratum/EnumEntry.scala
- enumeratum-core/src/test/scala/enumeratum/EnumSpec.scala
- enumeratum-core/src/test/scala/enumeratum/Models.scala
> Implement stackable Camelcase, LowerCamelcase and Uncapitalised

- build.sbt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lloydmeta/enumeratum/142)
> Bump to Circe 0.8.0

- README.md
```
$curl -i http://www.argonaut.io
curl: (6) Could not resolve host: www.argonaut.io
```
whereas:
```
$curl -i argonaut.io | head
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 10201  100 10201    0     0  64824      0 --:--:-- --:--:-- --:--:-- 64974
HTTP/1.1 200 OK
Server: GitHub.com
Date: Thu, 21 Sep 2017 20:30:17 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 10201
Last-Modified: Sat, 20 Feb 2016 16:48:10 GMT
Access-Control-Allow-Origin: *
Expires: Thu, 21 Sep 2017 20:40:17 GMT
Cache-Control: max-age=600
Accept-Ranges: bytes
```
> Replace URL to argonaut homepage.

- build.sbt
Hi,
I bumped the circe version to the new release.
Cheers
> Bump circe version to 0.9.0

- README.md
- build.sbt
- enumeratum-scalacheck/src/test/scala/enumeratum/ScalacheckSpec.scala
- enumeratum-scalacheck/src/test/scala/enumeratum/ScalacheckTest.scala
- enumeratum-scalacheck/src/test/scala/enumeratum/values/ScalacheckSpec.scala
> Add ScalaJS support to enumeratum-scalacheck

- build.sbt
https://github.com/circe/circe/releases/tag/v0.9.2
> Bump circe to v0.9.2

- build.sbt
https://github.com/circe/circe/releases/tag/v0.9.3
> Bump circe to 0.9.3

- .travis.yml
- build.sbt
- project/plugins.sbt
Part of supporting scala 2.13.0-M5 builds
> scala 2.13.0-M5 build

- build.sbt
* add play-json
* equivalent scala.js builds
> Extend 2.13 build

- build.sbt
https://github.com/circe/circe/releases/tag/v0.10.1
> Bump circe to 0.10.1

- build.sbt
note this drops support for play 2.6
> use play 2.7 for all scalas > 2.10

- .travis.yml
- build.sbt
- enumeratum-core/src/main/scala/enumeratum/values/ValueEnum.scala
- enumeratum-play-json/src/main/scala/enumeratum/values/EnumFormats.scala
- enumeratum-play/src/main/scala/enumeratum/UrlBinders.scala
- enumeratum-play/src/main/scala/enumeratum/values/UrlBinders.scala
- enumeratum-play/src/test/scala/enumeratum/PlayEnumSpec.scala
- enumeratum-play/src/test/scala/enumeratum/values/PlayValueEnumHelpers.scala
- macros/src/main/scala/enumeratum/ValueEnumMacros.scala
- project/plugins.sbt
> Scala 2.13.0-RC2 build

- build.sbt
Update quill from 2.3.3 to 3.2.1.
> Update quill to 3.2.1

- build.sbt
Play 2.7.3 is around the corner, not yet officially announced.
Related to #239 
--- 
It's official :champagne: https://discuss.lightbend.com/t/play-2-7-3-released/4459
> Re-enable Play and Play-JSON for Scala 2.13

- build.sbt
[scala-steward](https://github.com/fthomas/scala-steward/) is quite good at this, give it a go? @lloydmeta
> upgrade doobie to 0.7.0

- .travis.yml
Signed-off-by: lloydmeta <lloydmeta@gmail.com>
> Try openjdk8

- build.sbt
@lloydmeta Hi! Could you, please, release a new version of enumeratum-doobie after merging this?
Thanks a lot!
> Bump doobie to 0.8.4

- project/Versions.scala
Signed-off-by: lloydmeta <lloydmeta@gmail.com>
> Release core v1.5.15

- enumeratum-play/src/main/scala/enumeratum/UrlBinders.scala
- enumeratum-play/src/test/scala/enumeratum/UrlBindersSpec.scala
resolving the following issue: https://github.com/lloydmeta/enumeratum/issues/309
> change UrlBinder error message to use the enum

- README.md
Included reference to a required Play dependency change in README.md
> Add enumeratum-play dependency notes to readme

- enumeratum-core/src/test/scala/enumeratum/values/ValueEnumSpec.scala
- macros/src/main/scala-3/enumeratum/ValueEnumMacros.scala
> Updated the Scala 3 macro to support entries with type parameters

- build.sbt
- project/plugins.sbt
Duplicates #402 but with a ScalaJS bump on top. @mateuszkubuszok said he's busy these days so I figured I could try moving the needle at least a tiny bit, and see what fails next.
> Migrate from Scala native 0.4 to 0.5

- build.sbt
> Make dependency on macros cross-platform
